moods_and_tenses = {
    # mlconjug3 doesn't support all the moods and tenses :(, do not uncomment
    # 'mood': {
    #   'tense': person
    #   'tense': person
    # }
    'Indicatif': {
        'Présent': ['je', 'tu', 'il (elle, on)', 'nous', 'vous', 'ils (elles)'],
        'Imparfait': ['je', 'tu', 'il (elle, on)', 'nous', 'vous', 'ils (elles)'],
        'Futur': ['je', 'tu', 'il (elle, on)', 'nous', 'vous', 'ils (elles)'],
        'Passé Simple': ['je', 'tu', 'il (elle, on)', 'nous', 'vous', 'ils (elles)'],
    },
    'Conditionnel': {
        'Présent': ['je', 'tu', 'il (elle, on)', 'nous', 'vous', 'ils (elles)'],
    },
    'Subjonctif': {
        'Présent': ['je', 'tu', 'il (elle, on)', 'nous', 'vous', 'ils (elles)'],
        'Imparfait': ['je', 'tu', 'il (elle, on)', 'nous', 'vous', 'ils (elles)'],
    },
    'Imperatif': {
        'Imperatif Présent': '',
    },
    'Participe': {
        'Participe Présent': '',
        # 'Participe Passé': ['masculin singuler', 'masculin pluriel', 'feminin singulier', 'feminin pluriel'],
    },
}

irregular_verbs = [
    "abattre",
    "absoudre",
    "se abstenir",
    "acheter",
    "accroître",
    "accueillir",
    "acquérir",
    "aller",
    "apercevoir",
    "apparaître",
    "appartenir",
    "appeler",
    "apprécier",
    "apprendre",
    "assaillir",
    "asseoir",
    "assiéger",
    "atteindre",
    "avoir",
    "battre",
    "boire",
    "bouillir",
    "broyer",
    "céder",
    "clore",
    "combattre",
    "commencer",
    "comparaître",
    "comprendre",
    "compromettre",
    "concevoir",
    "conclure",
    "concourir",
    "conduire",
    "confire",
    "connaître",
    "conquérir",
    "construire",
    "contenir",
    "contredire",
    "convaincre",
    "convenir",
    "coudre",
    "courir",
    "couvrir",
    "craindre",
    "croire",
    "croître",
    "cueillir",
    "cuire",
    "déceler",
    "décevoir",
    "découvrir",
    "décrire",
    "déduire",
    "défaire",
    "déplaire",
    "détruire",
    "devenir",
    "devoir",
    "dire",
    "disparaître",
    "dissoudre",
    "distraire",
    "dormir",
    "éclore",
    "écrire",
    "élire",
    "émettre",
    "employer",
    "enclore",
    "enfuir",
    "entreprendre",
    "entretenir",
    "envoyer",
    "équivaloir",
    "éteindre",
    "être",
    "exclure",
    "extraire",
    "faillir",
    "faire",
    "falloir",
    "feindre",
    "fuir",
    "geler",
    "haïr",
    "haleter",
    "harceler",
    "inclure",
    "inscrire",
    "instruire",
    "interdire",
    "intervenir",
    "introduire",
    "jeter",
    "joindre",
    "lancer",
    "lever",
    "lire",
    "luire",
    "maintenir",
    "manger",
    "méconnaître",
    "médire",
    "se méprendre",
    "mettre",
    "modeler",
    "moudre",
    "mourir",
    "mouvoir",
    "naître",
    "nuire",
    "obtenir",
    "offrir",
    "omettre",
    "ouvrir",
    "paître",
    "paraître",
    "parcourir",
    "parvenir",
    "payer",
    "peindre",
    "peler",
    "percevoir",
    "permettre",
    "peser",
    "placer",
    "plaindre",
    "plaire",
    "pleuvoir",
    "poursuivre",
    "pourvoir",
    "pouvoir",
    "prédire",
    "prendre",
    "prescrire",
    "prévaloir",
    "prévenir",
    "prévoir",
    "promettre",
    "recevoir",
    "reconnaître",
    "recueillir",
    "réduire",
    "rejoindre",
    "renaître",
    "renvoyer",
    "résoudre",
    "restreindre",
    "revoir",
    "rire",
    "rompre",
    "satisfaire",
    "savoir",
    "séduire",
    "sentir",
    "servir",
    "souffrir",
    "soumettre",
    "sourire",
    "souscrire",
    "soutenir",
    "se souvenir",
    "suffire",
    "suivre",
    "surprendre",
    "survenir",
    "survivre",
    "taire",
    "se taire",
    "teindre",
    "tenir",
    "transcrire",
    "transmettre",
    "tressaillir",
    "vaincre",
    "valoir",
    "venir",
    "vêtir",
    "vivre",
    "voir",
    "vouloir"
]

congratulations = [
    "Dix points pour Griffondor! 🧙",
    "Vous êtes quoi, un natif? 👀",
    "+1 😌",
    "+1 ✔️",
    "+1 🔥",
]

mistakes = [
    "Noup",
    "Noo",
]

verb_doesnt_exist = [
    "errore a trabocchetto :) (no points)",
]
